# Generated by Django 3.1.7 on 2021-03-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20210309_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
